### ISSUE TITLE
Component and Prop descriptions still missing

### ISSUE THREAD

**Issue by janrembold** [pixtron/storybook-addon-docs-stencil#1]
Hi @pixtron,

just stumbled over your project because I was missing all my stencil code docs in the storybook docs view.
I installed your plugin but don't see any more descriptions. :(

You can see a minimal demo repo here: https://github.com/janrembold/stencil-storybook-minimal

There is no component nor param description visible in storybook. But the auto-generated docs.json shows all `docs` correctly.

<img width="1084" alt="storybook-missing-docs" src="https://user-images.githubusercontent.com/4015313/106390621-8718a080-63e9-11eb-8367-10915081584d.png">

Am I missing something here?
Thanks for any advice!

**Comment by pixtron** [comment]
I just added a troubleshooting section to the readme. In your case you have to 

- set `docs.extractArgTypes` and `docs.extractComponentDescription` in `.storybook/preview.js`
- hint the used component in your stories `export default {component: 'my-component'}`

https://github.com/pixtron/storybook-addon-docs-stencil#troubleshooting

Could you close the issue, if that works for you?

**Comment by janrembold** [comment]
Works perfectly fine now!!! 
Thanks for the super quick response!
