### ISSUE TITLE
Prop Descriptions still missing from MDX Stories

### ISSUE THREAD

**Issue by johnmcase** [pixtron/storybook-addon-docs-stencil#11]
**Describe the bug**
When writing stories using [MDX](https://storybook.js.org/docs/react/writing-docs/mdx) component property descriptions are not populated in the ArgsTable.

**Steps to Reproduce**
1. Clone the reproduction repo below and run it
2. Compare the Docs page for the `JS Stories` and `MDX Stories`

**Screenshots**

***JS***
![image](https://user-images.githubusercontent.com/314819/150438554-f7fec39c-afbd-4d7d-967b-ffdd9d85e8e9.png)

***MDX***
![image](https://user-images.githubusercontent.com/314819/150438590-07437948-5f3a-4d05-b7b3-82e081e7ca58.png)

**Repro**
[Minimal Reproduction](https://github.com/johnmcase/storybook-stencil-mdx)

**Expected behavior**
I expect the MDX ArgsTable to have descriptions in it

**System**
Environment Info:

  System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz
  Binaries:
    Node: 16.1.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 7.11.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 97.0.4692.71
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.62)
  npmPackages:
    @storybook/addon-actions: ^6.4.13 => 6.4.13
    @storybook/addon-essentials: ^6.4.13 => 6.4.13
    @storybook/addon-links: ^6.4.13 => 6.4.13
    @storybook/web-components: ^6.4.13 => 6.4.13

**Comment by johnmcase** [comment]
I should also add that I did follow the directions in the Troubleshooting section of the readme [here](https://github.com/pixtron/storybook-addon-docs-stencil#troubleshooting)

**Comment by pixtron** [comment]
That should fix your issue:

```
diff --git a/src/components/my-component/my-component.stories.mdx b/src/components/my-component/my-component.stories.mdx
index fee5565..1b3ecd8 100644
--- a/src/components/my-component/my-component.stories.mdx
+++ b/src/components/my-component/my-component.stories.mdx
@@ -3,7 +3,7 @@ import { html } from 'lit-html';

 <Meta
   title='My Component/MDX Stories'
-  component='my-component' />
+  component={'my-component'} />

 export const Template = (args) =>  html`
   <my-component
(END)
```
