### ISSUE TITLE
Story deeplinks with`args` doesn't work

### ISSUE THREAD

**Issue by weaintplastic** [pixtron/storybook-addon-docs-stencil#2]
Hey there. Thank you for creating this library.

When using it I've noticed that the `args` included in a deeplink to a story doesn't change the rendered component as expected.

When changing one of the args via a control, the rendered component immediately reflects that change, as well as the URL, is updated with the correct query string like `http://localhost:6006/?path=/story/button--default&args=shape:pill`

When sharing this URL it is expected, that the rendered output, as well as the value of the control, is reflecting this accordingly. But when using this library, this deep linking functionality doesn't work anymore.

I'm not sure if this is a problem with this library or with the docs addon. I'd appreciate any help.

**Comment by pixtron** [comment]
Should be fixed with 6601bbe. Although there seems to be a bug in storybookjs/storybook/issues/17063
