### ISSUE TITLE
Story not updating changes in readme.md

### ISSUE THREAD

**Issue by janrembold** [pixtron/storybook-addon-docs-stencil#3]
Hi @pixtron ,

I'm running Stencil with `stencil build --watch --docs --no-open` and Storybook with `start-storybook -s ./dist -p 6006`.

Changes on components' documentations get reflected immediately with a reload of Storybook.
But changes inside readme.md files are not respected. The stencil process is not updating after a change in a .md file

Is there a way to `watch`  and update the generated `docs.json` for readme.md files?

Thanks in advance!
Jan

**Comment by pixtron** [comment]
Hi @janrembold 

To watch the `readme.md` files and regenerate `docs.json` seems to be a stencil cli issue.

**Comment by janrembold** [comment]
@pixtron you're right. The "feature" of not watching .md files is even hardcoded: https://github.com/ionic-team/stencil/blob/master/src/compiler/build/watch-build.ts#L161

Will send an issue and maybe a PR if they are interested...
