### ISSUE TITLE
Docs addon sets incorrect attribute for camelCase Prop

### ISSUE THREAD

**Issue by evgeny29** [pixtron/storybook-addon-docs-stencil#8]
For a pure web-component, this needs to be `acc[item.attr] =` to ensure the attribute is set with '-', not with camelCase.
https://github.com/pixtron/storybook-addon-docs-stencil/blob/e87eece216d22d0643057cf15aedb168d83734b7/src/index.ts#L94

**Comment by pixtron** [comment]
Can be configured since version 6.4.1. See this [comment](https://github.com/pixtron/storybook-addon-docs-stencil/pull/9#issuecomment-1030706894)
